<a href="https://colab.research.google.com/github/priyanshurishi/datahandling/blob/main/dataHandling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as mp

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
df3=pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
#Python Program Illustrating
#numpy.reshape() method
import numpy as geek
array=geek.arange(8)
print("Original array :\n" ,array)

#shape array with 2 rows and 4 columns
array=geek.arange(8).reshape(2,4)
print("\n array reshaped with 2 row and 4 columns : \n",array)

#shape array with 4 rows and 2 columns
array=geek.arange(8).reshape(4,2)
print("\n array reshaped with 4 row and 2 columns : \n",array)

#Construct 3D array
array=geek.arange(8).reshape(2,2,2)
print("Original array reshaped to 3D :\n", array)


Original array :
 [0 1 2 3 4 5 6 7]

 array reshaped with 2 row and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

 array reshaped with 4 row and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Original array reshaped to 3D :
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
import numpy as np

In [ ]:
df= pd.read_excel("/content/sales-funnel.xlsx")
df.head()

Account                          Name  ...  Price     Status
0   714466               Trantow-Barrows  ...  30000  presented
1   714466               Trantow-Barrows  ...  10000  presented
2   714466               Trantow-Barrows  ...   5000    pending
3   737550  Fritsch, Russel and Anderson  ...  35000   declined
4   146832                  Kiehn-Spinka  ...  65000        won

[5 rows x 8 columns]

In [ ]:
pd.pivot_table(df,index=["Name"])

Account   Price  Quantity
Name                                                   
Barton LLC                     740150   35000  1.000000
Fritsch, Russel and Anderson   737550   35000  1.000000
Herman LLC                     141962   65000  2.000000
Jerde-Hilpert                  412290    5000  2.000000
Kassulke, Ondricka and Metz    307599    7000  3.000000
Keeling LLC                    688981  100000  5.000000
Kiehn-Spinka                   146832   65000  2.000000
Koepp Ltd                      729833   35000  2.000000
Kulas Inc                      218895   25000  1.500000
Purdy-Kunde                    163416   30000  1.000000
Stokes LLC                     239344    7500  1.000000
Trantow-Barrows                714466   15000  1.333333

In [ ]:
#REverse of string
str="This is a car"
str[::-1]

'rac a si sihT'

In [ ]:
#split
str1="I am a cricketer"
str1.split()

['I', 'am', 'a', 'cricketer']

In [ ]:
#split
str2="I_am_a_cricketer"
str1.split('_')

['I am a cricketer']

In [ ]:
import nltk

In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import 